---
- name: Make sure data folder exists
  file:
    path: /root/data/coredns/
    state: directory

- name: Copy configuration files
  copy:
    dest: /root/data/coredns/
    src: "{{ item }}"
  loop:
    - Corefile
    - db.192.168.80
    - db.iac.estgv
    - docker-compose.yml
    
- name: Pull coredns/coredns docker image
  docker_image:
    name: coredns/coredns
    tag: latest
    source: pull
    state: present

- name: Disable systemd-resolved service
  service:
    name: systemd-resolved
    state: stopped

- name: Change /etc/systemd/resolved.conf
  lineinfile:
    path: /etc/systemd/resolved.conf
    line: "{{ item.line }}"
    regexp: "{{ item.string }}"
    firstmatch: yes
    state: present
  loop:
    - line: DNS=192.168.0.7
      string: DNS=
    - line: DNSStubListener=no
      string: DNSStubListener=

- name: Create symbolink link to /etc/resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    path: /etc/resolv.conf
    state: link

- name: Restart systemd-resolved service
  service:
    name: systemd-resolved
    state: started

- name: Start docker-compose.yml definition
  docker_compose:
    project_name: coredns
    project_src: /root/data/coredns/